version: '2'
services:  
  spark:
      image: jupyter/pyspark-notebook
      ports:
        - 8088:8088
        - 8042:8042        
        - 8888:8888
        - 4040-4080:4040-4080
        - 9999:9999
      volumes:
        - ./spark_jobs:/home/jovyan/work                
  

